import { Stream } from "../stream/stream.js";
import { Engine } from "./engine.js";

let streamErrorCounter: { [streamID: string]: number } = {} // streamID to count
/**
 * handles events generated by exthos modules
 * USAGE: `engine.onAny(defaultEngineEventHandler)`
 * @param eventName 
 * @param eventObj 
 */
function defaultEngineEventHandler(this: Engine, eventName: string, eventObj: { stream: Stream }) {
    let self = this
    if (eventName === "engine.stream.error") {
        console.log(`           ${eventName}>>${JSON.stringify(eventObj)}`);
        streamErrorCounter[eventObj.stream.streamID] = streamErrorCounter[eventObj.stream.streamID] || 0
        streamErrorCounter[eventObj.stream.streamID] = streamErrorCounter[eventObj.stream.streamID] + 1
        if (streamErrorCounter[eventObj.stream.streamID] === 5) {
            // remove the stream if error received 5 times
            self.remove(eventObj.stream)
        }
    } else {
        console.log(`           ${eventName}>>${JSON.stringify(eventObj)}`);
    }
}

export { defaultEngineEventHandler }